<html>
	<head>
		<title>Feelings, Food and Genetic Engineering</title>
	</head>
	<body>
		<div id="story">
			<h1>Feelings, Food and Genetic Engineering</h1>
			<p>As the old saying goes: A person's got to eat! But reliably feeding the global population is easier said than done. This is why, in order to supply enough food around the world, farmers and scientists have begun to incorporate a few controversial techniques in the way they grow and produce the stuff that goes into our meals.</p>
			<p>For the past 10,000 years, humans have been using technology to improve the way we feed our species, but some of the techniques developed in the past century are raising concerns among some politicians and environmentalists alike. In the last few decades we have seen an introduction of Genetically Modified Organisms (GMOs) into the marketplace.</p>
			<p>To create a GMO, scientists artificially incorporate genetic material from other plants and animals into harvests in order to create crops that exhibit specific new traits. For example, modified cotton seeds have been designed to help the resulting plants withstand insect attacks, which allows farmers to avoid use of synthetic chemicals and other pesticides.</p>
			<p>One of the motivations behind this kind of development is the fact that the United Nations predicts that the global population will hit 9 billion people by 2050. Feeding that many people is going to take a lot of food, and forecasters are concerned that we will not be able to meet the demand if the current trends do not change.</p>
			<p>The promise that genetically modified crops could help feed the world is at least as old as the commercialization of the first transgenic seeds in the mid-1990s. The corporations that helped turn genetically engineered crops into a multibillion-dollar business, including the large chemical companies Monsanto, Bayer, and DuPont, promoted the technology as part of a life science revolution that would greatly increase food production. So far it’s turned out, for a number of reasons, to have been a somewhat empty promise.</p>
			<p>So far, the short list of transgenic crops used directly for food includes virus-resistant papaya grown in Hawaii, Bt sweet corn recently commercialized in the United States by Monsanto, and a few varieties of squash that resist plant viruses. That list could be about to grow, however, as the Indonesian agricultural agency expects to approve a blight-resistant potato soon. There are also a wide variety of inedible applications for GMOs outside of food production, ranging from energy generators to providers of transplant organs.</p>
			<p>But regardless of the use case, tampering with something as complex as genetic information has the potential for unexpected side effects. After all, these alterations are generally designed to change the organism's metabolism, growth rate, or response to external environmental factors. These consequences have the potential to influence not only the GMO itself, but also the natural environment in which that organism is allowed to proliferate.</p>
			<p>These kinds of risks are part of the reason that the FDA regulates GM foods as part of the coordinated framework of federal agencies that also includes the Environmental Protection Agency (EPA) and the United States Department of Agriculture (USDA). However, critics of this system complain that the regulation is opt-in, meaning there is no centralized government body responsible for evaluating the products.</p>
			<p>Clearly we need to find a safe, healthy, sustainable way to feed the world for generations to come. For now all eyes are on researchers to decide whether or not GMOs can meet all of those conditions; if not, we will just have to cross our fingers hoping for the next agricultural revolution.</p>
		</div>
		<div id="continue"><a href="next">When you are finished reading the story, please click here to continue</a></div>
	</body>
</html>